backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blogs"
    label: "Blogs"
    files:
      - file: "_data/blogs.json"
        label: "Blogs Data"
        name: "blogs"
        format: "json"
        fields:
          - label: "Posts"
            name: "items"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Type", name: "type", widget: "select", options: ["Blog", "Tutorial"] }
              - { label: "Tag", name: "tag", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image URL", name: "imageUrl", widget: "image" }
              - { label: "Video ID", name: "videoId", widget: "string", required: false }
              - { label: "Code", name: "code", widget: "text", required: false }
              - { label: "URL", name: "url", widget: "string" }
